name: Deploy the docs to RTD

on:
  push:
    branches: [ main ]

env:
  REPO_SSH: git@github.com:SWHL/TestRTD.git
  CLONE_URL: ${{ github.event.repository.clone_url }}
  USER_NAME: ${{ github.event.repository.owner.name }}
  USER_EMAIL: ${{ github.event.repository.owner.email }}
  SUBMMIT_BRANCH: main

jobs:
  Deploy_TO_RTD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Set SSH Environment
        env:
          DEPLOY_KEYS: ${{ secrets.DEPLOY_KEYS }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEYS" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
          git config --global user.name $USER_NAME
          git config --global user.email $USER_EMAIL

      - name: Summit repo to docs branch.
        run: |
          pip install sphinx
          sphinx-apidoc -o source/ ./src -f -E -M

          git add .
          git status
          git remote remove origin
          git remote add origin ${REPO_SSH}
          git commit -m 'Actions auto update' && git push -f origin ${SUBMMIT_BRANCH} || echo "No changes to commit"